theme = "PaperMod"
baseURL = ""
languageCode = "es-es"
title = "Santuario Dana Tagoro"

[params]
description = "El Santuario Dana Tagoro es un refugio comprometido con el rescate y cuidado de animales."
og_image = "/images/logo.jpg"
sobre_nosotros = "El Santuario Dana Tagoro es un refugio comprometido con el rescate y cuidado de animales en situación de abandono o maltrato."
donaciones_texto = "Aquí podrás encontrar nuestros datos bancarios o métodos alternativos para realizar tu donación."
relativeURLs = true
canonifyURLs = true
disableFingerprinting = true

custom_css = ["css/style.css"]
favicon32 = ["favicon/favicon-32x32.png"]
favicon16 = ["favicon/favicon-16x16.png"}
appletouch_favicon = ["favicon/appletouch_favicon.png"]
web_manifest = ["favicon/site.webmanifest"]